### ISSUE TITLE
Cherry pick Pull Requests / PRs from https://github.com/todotxt/todo.txt/pulls

### ISSUE THREAD

**Issue by clach04** [too-much-todotxt/spec#5]
Potentially blocked by [issue Review/compare https://github.com/todotxt/todo.txt spec](https://github.com/too-much-todotxt/spec/issues/2)

https://github.com/todotxt/todo.txt/pulls

  * [x] https://github.com/todotxt/todo.txt/pull/87 - flip colors when the user prefers a dark color scheme
      * https://github.com/too-much-todotxt/legacy_todo.txt/tree/todo.txt_PR87_make-image-theme-sensitive
      * https://github.com/too-much-todotxt/spec/issues/18
  * https://github.com/todotxt/todo.txt/pull/83 - Add formal grammar definition of format
      * https://github.com/too-much-todotxt/legacy_todo.txt/tree/todo.txt_PR83_EBNF_formal_gramar
  * [x] https://github.com/todotxt/todo.txt/pull/74 for [Project and Context case sensitive](https://github.com/todotxt/todo.txt/issues/73)
      * https://github.com/too-much-todotxt/legacy_todo.txt/tree/todo.txt_issue73
      * https://github.com/too-much-todotxt/spec/issues/17
  * [x] https://github.com/todotxt/todo.txt/pull/68 - retain SVG (... or PNG... potentially useful on small screens, for example phones)
      * https://github.com/too-much-todotxt/legacy_todo.txt/tree/todo.txt_PR68_textdesc
      * https://github.com/too-much-todotxt/spec/issues/20
  * https://github.com/todotxt/todo.txt/pull/21 - with the full history in this repo, this will be easier to explain

Where possible make-use of co-authors https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by clach04** [comment]
https://github.com/too-much-todotxt/legacy_todo.txt/branches created to aid in this.

DONE new branch in https://github.com/too-much-todotxt/legacy_todo.txt/ with new-lines in paragraphs for ease of reading AND 7-bit clean us-ascii - see https://github.com/too-much-todotxt/legacy_todo.txt/tree/newlines_in_paragraphs
